apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  BACKEND_API_URL: "http://aa59d2b6306434b818d72a12f3f947a6-1656409143.us-west-1.elb.amazonaws.com/"  # Use the actual LoadBalancer URL here
